### ISSUE TITLE
404 NOT FOUND || https://mimpy-id.000webhostapp.com/registrasi.php

### ISSUE THREAD

**Issue by codewithrafli** [hairullana/mimpy.id-laravel#1]
![image](https://user-images.githubusercontent.com/70202056/153527945-ff4f75c3-4601-499a-be19-2ff54a459dcb.png)

![image](https://user-images.githubusercontent.com/70202056/153527974-f44941c8-d8d8-4780-92fc-a73e778dfa7a.png)

waktu saya pencet bagian daftar sekarang itu navigate nya masih ke https://mimpy-id.000webhostapp.com/registrasi.php yang seharusnya ke https://mimpy-id.000webhostapp.com/register

**Comment by hairullana** [comment]
Terima kasih koreksinya bang
